# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================

spring:
  application:
    name: ccdapp2
  # MONGODB (MongoProperties)
#  profiles:
#    active: dev
  #    include: # additional configuration profile options such as swagger etc.
  #    include: # additional configuration profile options such as swagger etc.
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
#      uri: mongodb://app_api:W!%26EK_%23rQZaLn2dv@ccte-mongodb-dev.epa.gov/dev_datamart_comptox?authSource=admin
#      auto-index-creation: true;
      password: ${CCD_MONGO_PASSWORD}
      authentication-database: ${CCD_MONGO_AUTH}
      database: ${CCD_MONGO_DB}
      username: ${CCD_MONGO_USERNAME}
      host: ${CCD_MONGO_HOST}

# Logging
logging:
  level:
    gov.epa.ccte.api.*: info
    org.springframework: info
    org.springframework.data.mongodb.core.MongoTemplate:  info

# server
server:
  servlet:
    context-path: /
  #port: 9400



# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
