# ===================================================================
# Spring Boot configuration for the "external production" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================


spring:
  application:
    name: ccdapp2
  #    include: # additional configuration profile options such as swagger etc.
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
      uri: ${CCD_MONGO_URI}
      database: ${CCD_MONGO_DB}
# Logging
logging:
  level:
    gov.epa.ccte.api.*: info
    org.springframework: info
    org.springframework.data.mongodb.core.MongoTemplate: debug
# server
server:
  servlet:
    context-path: /
  #port: 9400
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
