name: Container-security-scan

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ dev, staging ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-push:

    runs-on: th878
    environment: ${{ github.head_ref || github.ref_name }}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - run: git lfs pull

      - name: Docker build
        run: docker build -f Dockerfile -t ccdapp2-security-${{ github.head_ref || github.ref_name }} .

      - name: Create Output Folder
        run: mkdir output    
          
      - name: Run security scan on the container
        uses: aquasecurity/trivy-action@0.12.0
        id:   scan
        with:
          image-ref: 'ccdapp2-security-${{ github.head_ref || github.ref_name }}'
          format: template
          template: "@/contrib/html.tpl"
          output: ./output/trivy-report.html
          severity: 'CRITICAL,HIGH' 

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with: 
          name: container-scan-report
          path: output
          
      - name: remove previous trivy report
        run: rm -rf /data/watchtower/ccd/container-results/app2/trivy-report.html
   
      - name: download artifacts to the computer    
        uses: actions/download-artifact@v3
        with:
          name: container-scan-report
          path: /data/watchtower/ccd/container-results/app2
          
     
