name: Application-security-scan

on:
  schedule:
    - cron: '00 9 * * 1,3,5'
    
jobs:
  zap-scan:
    runs-on: "th878" 
    steps:
       
    - name: ZAP Scan
      uses: zaproxy/action-api-scan@v0.5.0
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
         format: openapi
         target: 'https://ccte-api-ccd-dev.epa.gov/ccdapp2/v3/api-docs'
         cmd_options: '-a'
